#!/bin/bash

# 本ファイルが配置されているディレクトリに移動
cd `dirname $0`

# 定数読み込み
source ./batch_settings.txt
# BDBに登録されたログEntryをBigQueryに移動させるクラス(java)
CHECK_BDB_DISK_USAGE_CLASS="jp.reflexworks.batch.CheckBDBDiskUsageApp"
# サーバタイプ : Manifest
SERVER_TYPE_MNF="mnf"
# サーバタイプ : Entry
SERVER_TYPE_ENTRY="entry"
# サーバタイプ : インデックス
SERVER_TYPE_IDX="idx"
# サーバタイプ : 全文検索インデックス
SERVER_TYPE_FT="ft"
# サーバタイプ : 採番・カウンタ
SERVER_TYPE_AL="al"

# BDBディスク使用量チェック
java -cp $CLASSPATH $JAVA_OPTIONS $CHECK_BDB_DISK_USAGE_CLASS $BDBSERVERLIST_FILEPATH_MNF $SERVER_TYPE_MNF
java -cp $CLASSPATH $JAVA_OPTIONS $CHECK_BDB_DISK_USAGE_CLASS $BDBSERVERLIST_FILEPATH_ENTRY $SERVER_TYPE_ENTRY
java -cp $CLASSPATH $JAVA_OPTIONS $CHECK_BDB_DISK_USAGE_CLASS $BDBSERVERLIST_FILEPATH_IDX $SERVER_TYPE_IDX
java -cp $CLASSPATH $JAVA_OPTIONS $CHECK_BDB_DISK_USAGE_CLASS $BDBSERVERLIST_FILEPATH_FT $SERVER_TYPE_FT
java -cp $CLASSPATH $JAVA_OPTIONS $CHECK_BDB_DISK_USAGE_CLASS $BDBSERVERLIST_FILEPATH_AL $SERVER_TYPE_AL

