#!/bin/bash

# 本ファイルが配置されているディレクトリに移動
cd `dirname $0`

# 定数読み込み
source ./batch_settings.txt
# 指定されたステータスの名前空間リスト作成クラス(java)
WRITE_NAMESPACES_CLASS="jp.reflexworks.batch.WriteNamespacesApp"
# サーバごとの指定されたステータスの名前空間リスト作成クラス(java)
WRITE_NAMESPACES_EACH_SERVER_CLASS="jp.reflexworks.batch.WriteNamespacesEachServerApp"
# BDBサーバリスト作成クラス(java)
WRITE_BDBSERVERS_CLASS="jp.reflexworks.batch.WriteBDBServersApp"
# 有効なサービスステータス (複数の場合カンマ区切り)
VALID_SERVICESTATUS="creating,staging,production,blocked,toproduction,tostaging,maintenance"
# サーバタイプ : Manifest
SERVER_TYPE_MNF="mnf"
# サーバタイプ : Entry
SERVER_TYPE_ENTRY="entry"
# サーバタイプ : インデックス
SERVER_TYPE_IDX="idx"
# サーバタイプ : 全文検索インデックス
SERVER_TYPE_FT="ft"
# サーバタイプ : 採番・カウンタ
SERVER_TYPE_AL="al"

echo '[write_list] start'

# サービス名と名前空間の一覧をファイルに出力 (有効なサービス)
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_CLASS $VALID_NAMESPACELIST_FILEPATH $VALID_SERVICESTATUS

# サービス名と名前空間の一覧をファイルに出力 (バックアップ対象サービス、サーバごとにファイル出力)
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $BACKUP_NAMESPACELIST_EACH_SERVER_DIRPATH_MNF $BACKUP_SERVICESTATUS $SERVER_TYPE_MNF
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $BACKUP_NAMESPACELIST_EACH_SERVER_DIRPATH_ENTRY $BACKUP_SERVICESTATUS $SERVER_TYPE_ENTRY
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $BACKUP_NAMESPACELIST_EACH_SERVER_DIRPATH_IDX $BACKUP_SERVICESTATUS $SERVER_TYPE_IDX
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $BACKUP_NAMESPACELIST_EACH_SERVER_DIRPATH_FT $BACKUP_SERVICESTATUS $SERVER_TYPE_FT
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $BACKUP_NAMESPACELIST_EACH_SERVER_DIRPATH_AL $BACKUP_SERVICESTATUS $SERVER_TYPE_AL

# サービス名と名前空間の一覧をファイルに出力 (有効なサービス、サーバごとにファイル出力)
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $VALID_NAMESPACELIST_EACH_SERVER_DIRPATH_MNF $VALID_SERVICESTATUS $SERVER_TYPE_MNF
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $VALID_NAMESPACELIST_EACH_SERVER_DIRPATH_ENTRY $VALID_SERVICESTATUS $SERVER_TYPE_ENTRY
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $VALID_NAMESPACELIST_EACH_SERVER_DIRPATH_IDX $VALID_SERVICESTATUS $SERVER_TYPE_IDX
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $VALID_NAMESPACELIST_EACH_SERVER_DIRPATH_FT $VALID_SERVICESTATUS $SERVER_TYPE_FT
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_NAMESPACES_EACH_SERVER_CLASS $VALID_NAMESPACELIST_EACH_SERVER_DIRPATH_AL $VALID_SERVICESTATUS $SERVER_TYPE_AL

# サーバ名とURLの一覧をファイルに出力
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_BDBSERVERS_CLASS $BDBSERVERLIST_FILEPATH_MNF $SERVER_TYPE_MNF
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_BDBSERVERS_CLASS $BDBSERVERLIST_FILEPATH_ENTRY $SERVER_TYPE_ENTRY
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_BDBSERVERS_CLASS $BDBSERVERLIST_FILEPATH_IDX $SERVER_TYPE_IDX
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_BDBSERVERS_CLASS $BDBSERVERLIST_FILEPATH_FT $SERVER_TYPE_FT
java -cp $CLASSPATH $JAVA_OPTIONS $WRITE_BDBSERVERS_CLASS $BDBSERVERLIST_FILEPATH_AL $SERVER_TYPE_AL

echo '[write_list] end'

